### ISSUE TITLE
Will this library support forge / neoforge ?

### ISSUE THREAD

**Issue by sakurawald** [Patbox/sgui#31]
The library works great in fabric platform, and i am curious about whether it will support some other platforms, like forge and bukkit ?
I mean, a library that provides a great abstraction on multi-platform.

**Comment by Patbox** [comment]
I don't have plans, as I don't use either pf these platforms.

With (Neo)Forge, someone could easily fork and port it, while also keeping full source compatibility in common code.

On bukkit like platforms it won't be really possible (or rather it won't make sense) as bukkit uses it's own abstraction instead of vanilla classes (so it won't work on common codepath)
